app/models.py
from datetime import datetime

from . import db


class User(db.Document):
    email = db.EmailField(required=True, unique=True)
    password = db.StringField(required=True)
    token = db.StringField(required=True)


class Release(db.EmbeddedDocument):
    name = db.StringField()


class Module(db.EmbeddedDocument):
    name = db.StringField()


class Project(db.Document):
    name = db.StringField(required=True, unique=True)
    modules = db.EmbeddedDocumentListField(Module)
    releases = db.EmbeddedDocumentListField(Release)


class Step(db.EmbeddedDocument):
    description = db.StringField()
    status = db.StringField()
    screenshot = db.StringField()


class Test(db.Document):
    number = db.IntField()
    module = db.StringField()
    description = db.StringField()
    status = db.StringField()
    rerun = db.BooleanField()
    date = db.DateTimeField(default=datetime.utcnow)
    tags = db.ListField(db.StringField())
    steps = db.EmbeddedDocumentListField(Step)

app/__init__.py
import os
import logging
from logging.handlers import RotatingFileHandler
from flask import Flask
from flask_mongoengine import MongoEngine
from config import config

db = MongoEngine()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    if not app.debug:
        if not os.path.exists('logs'):
            os.mkdir('logs')

        file_handler = RotatingFileHandler(
            filename='logs/elphy.log',
            maxBytes=10240,
            backupCount=10
        )

        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'
        ))
        file_handler.setLevel(logging.INFO)

        app.logger.addHandler(file_handler)
        app.logger.setLevel(logging.INFO)

    db.init_app(app)

    from .dashboard import dashboard as dashboard_blueprint
    app.register_blueprint(dashboard_blueprint, url_prefix='/dashboard/')

    from .errors import errors as errors_blueprint
    app.register_blueprint(errors_blueprint)

    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api/v1')

    return app

app/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import token, project, test  # noqa

app/dashboard/__init__.py
from flask import Blueprint

dashboard = Blueprint('dashboard', __name__)

from . import views  # noqa

app/dashboard/views.py
from flask import render_template, session
from mongoengine.errors import DoesNotExist
from mongoengine.context_managers import switch_collection

from . import dashboard
from ..models import Project, Test


@dashboard.route('/projects/<project_name>/releases/<release_name>')
def index(project_name, release_name):
    """
    Display the overall status of a release

    Cards:
    # Total number of tests
    # Total number of passed tests
    # Total number of failed tests
    # Total number of warning tests

    Graphs:
    # Pie chart showcasing passed, failed and warning percentage
    # Bar chart showcasing number of passed, failed and warning tests

    :raises 404: If project not in collection
    :raises 404: If project in collection but release not in releases
    """

    try:
        project = Project.objects.get(name=project_name)
        releases = Project.objects.filter(name=project.name).distinct('releases.name')
        if release_name not in releases:
            # Return 404 if project in collection but release not in releases
            return render_template('404.html'), 404
    except DoesNotExist:
        # Return 404 if project not in collection
        return render_template('404.html'), 404

    collection_name = f'{project_name}_{release_name}'
    with switch_collection(Test, collection_name) as TestCollection:
        tests = []
        numbers = set(TestCollection.objects.distinct('number'))
        modules = TestCollection.objects.distinct('module')

        # Remove the older tests and keep the latest rerun
        for num in numbers:
            test = TestCollection.objects.filter(number=num)
            latest_run_date = max(t.date for t in test)
            tests.append(
                [t for t in test if t.date == latest_run_date][0]
            )

        statuses = [test.status for test in tests]

        # Store the modules name and collection name in session
        # Used in module route to query the collection and populate sidenav
        session['modules'] = modules
        session['collection_name'] = collection_name

        total_tests = len(tests)
        total_passed = statuses.count('Passed')
        total_failed = statuses.count('Failed')
        total_warning = statuses.count('Warning')

        return render_template(
            'index.html',
            total_tests=total_tests,
            total_passed=total_passed,
            total_failed=total_failed,
            total_warning=total_warning,
            modules=modules
        )


@dashboard.route('/module/<name>')
def module(name):
    """
    Display the overall status of the Module in the release

    Cards:
    # Total number of tests
    # Total number of passed tests
    # Total number of failed tests
    # Total number of warning tests

    Table:
    Show the test number, description and status
    """

    modules = session['modules']
    collection_name = session['collection_name']

    # Store the module name in session
    # Used in test route to query the collection
    session['module'] = name

    with switch_collection(Test, collection_name) as TestCollection:
        tests_to_tablize = []
        module_tests = TestCollection.objects.filter(module=name)
        numbers = set(t.number for t in module_tests)

        # Remove the older tests and keep the latest rerun
        for num in numbers:
            test = list(filter(lambda t: t.number == num, module_tests))
            latest_run_date = max(t.date for t in test)
            tests_to_tablize.append(
                [t for t in test if t.date == latest_run_date][0]
            )

        statuses = [test.status for test in tests_to_tablize]

        total_tests = len(tests_to_tablize)
        passed = statuses.count('Passed')
        failed = statuses.count('Failed')
        warning = statuses.count('Warning')

        return render_template(
            'module.html',
            total_tests=total_tests,
            passed=passed,
            failed=failed,
            warning=warning,
            modules=modules,
            tests=tests_to_tablize
        )


@dashboard.route('/test/<number>')
def test(number):
    """
    Render the Test
    If no rerun, the test is rendered as an HTML Table
    If rereuns, the tests are rendered as collapsible
    """

    module = session['module']
    collection_name = session['collection_name']

    with switch_collection(Test, collection_name) as TestCollection:
        tests = TestCollection.objects(
            module=module,
            number=number
        )

        if len(tests) == 1:
            return render_template('test.html', test=tests[0])

        if len(tests) > 1:
            return render_template('tests.html', tests=tests)

app/templates/_macros.html
{% macro status_card(type_, count, color) %}
    <div class="card {{ color }} z-depth-2">
        <div class="card-content">
            <span class="card-title">{{ type_ }}</span>
            <p>{{ count }}</p>
        </div>
    </div>
{% endmacro %}

{% macro error_card(type_) %}
    <div class="col s6 offset-s3">
        <div class="card-panel z-depth-1">
            <h6 class="center green-text"><b>{{ type_ }}</b></h6>
        </div>
    </div>
{% endmacro %}

{% macro populate_sidenav(modules) %}
    {% for module in modules %}
        <li><a class="btn waves-effect waves-light" href="{{ url_for('dashboard.module', name=module) }}">{{ module }}</a></li>
    {% endfor %}
{% endmacro %}

{% macro render_steps(steps) %}
    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th>Screenshot</th>
            </tr>
        </thead>
        <tbody>
            {% for step in steps %}
                {% if step.status == "Fail" %}
                    <tr class="red lighten-2">
                {% elif step.status == "Warn" %}
                    <tr class="orange lighten-2">
                {% else %}
                    <tr>
                {% endif %}
                    <td>{{ step.description }}</td>
                    <td>
                        {% if step.screenshot %}
                            <img class="materialboxed" src="data:image/png;base64,{{ step.screenshot }}" width="25">
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Elphy Dashboard</title>

        <!--CSS-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        {% block head %}{% endblock %}
    </head>

    <body>
        <header>
            <!--Nav Bar-->
            <div class="navbar-fixed">
                <nav class="white">
                    <div class="nav-wrapper">
                        <div class="container">
                            <h6 class="brand-logo green-text"><b>Elphy</b></h6>
                            <ul class=right>
                                <li><a href="#" class="green-text"><i class="fas fa-sign-in-alt right"></i>Login</a></li>
                                <li></li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
            <!--Side Nav Bar-->
            <ul class="sidenav sidenav-fixed center" style="width: 200px; top: 65px;">
                <li id="module_banner">
                    <a class="green-text" style="padding-left: 50px;">Modules<i class="material-icons green-text right">view_modules</i></a>
                </li>
                {% block sidenav %}{% endblock %}
            </ul>
        </header>

        <main>
            <div class="container section">
                {% block content %}{% endblock %}
            </div>
        </main>
        <!--JS & JQuery-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        {% block script %}{% endblock %}
    </body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% from "_macros.html" import status_card, populate_sidenav %}

{% block sidenav %}
    {{ populate_sidenav(modules) }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col l3 m6 s12">
            {{ status_card("Tests", total_tests, "grey lighten-2") }}
        </div>
        <div class="col l3 m6 s12">
            {{ status_card("Passed", total_passed, "green lighten-2") }}
        </div>
        <div class="col l3 m6 s12">
            {{ status_card("Failed", total_failed, "red lighten-2") }}
        </div>
        <div class="col l3 m6 s12">
            {{ status_card("Warning", total_warning, "orange lighten-2") }}
        </div>
    </div>

    <div class="row">
        <div class="col l6 m12 s12">
            <div class="card z-depth-2">
                <div class="card-content">
                    <div id="statusPieChart" style="width:100%; height:300px;"></div>
                </div>
            </div>
        </div>
        <div class="col l6 m12 s12">
            <div class="card z-depth-2">
                <div class="card-content">
                    <div id="statusBarChart" style="width:100%; height:300px;"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script>
    var totalPassed = {{ total_passed|safe }};
    var totalFailed = {{ total_failed|safe }};
    var totalWarning = {{ total_warning|safe }};
    var totalTests = totalPassed + totalFailed + totalWarning;
</script>
<script src="{{ url_for('static', filename='graph.js') }}"></script>
{% endblock %}

app/templates/module.html
{% extends "base.html" %}
{% from "_macros.html" import status_card, populate_sidenav %}

{% block sidenav %}
    {{ populate_sidenav(modules) }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col l3 m6 s12">
            {{ status_card("Tests", total_tests, "grey lighten-2") }}
        </div>
        <div class="col l3 m6 s12">
            {{ status_card("Passed", passed, "green lighten-2") }}
        </div>
        <div class="col l3 m6 s12">
            {{ status_card("Failed", failed, "red lighten-2") }}
        </div>
        <div class="col l3 m6 s12">
            {{ status_card("Warning", warning, "orange lighten-2") }}
        </div>
    </div>

    <div class="row">
        <div class="input-field s12 hide-on-med-and-down">
            <i class="material-icons prefix">search</i>
            <input type="text" id="search">
            <label for="search">Search Tests</label>
        </div>
    </div>

    <div class="row">
        <table class="centered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Description</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody id="tests">
                {% for test in tests %}
                    {% if test.status == "Passed" %}
                        {% set row_class = "show-modal" %}
                    {% elif test.status == "Failed" %}
                        {% set row_class = "show-modal red lighten-2" %}
                    {% elif test.status == "Warning" %}
                        {% set row_class = "show-modal orange lighten-2" %}    
                    {% endif %}
                    <tr class="{{ row_class }}">
                        <td class="id">{{ test.number }}</td>
                        <td>{{ test.description }}</td>
                        <td>{{ test.status }}</td>
                    </tr>   
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div id="modal1" class="modal modal-fixed-footer">
        <div class="modal-content">
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
        </div>
    </div>

{% endblock%}

{% block script %}
<script>
    $(document).ready(function(){
        $(".modal").modal();

        // Filter the Tests Results Table
        $("#search").keyup(function() {
            const data = this.value;
            const testsRun = $("#tests").find("tr");
            
            if(data == "") {
                testsRun.show();
                return;
            }

            testsRun.filter(function() {
                $(this).toggle($(this).text().indexOf(data) > -1);
            });
        });

        $(".show-modal").click(function() {
            const xhr = $.ajax(
                "/dashboard/test/" + $(this).find(".id").html()
            ).done(function(data) {
                $(".modal-content").html(data);
                $(".modal").modal('open');
                $(".materialboxed").materialbox();
                $(".collapsible").collapsible();
            });
        });
    });
</script>
{% endblock %}

app/templates/test.html
{% from "_macros.html" import render_steps %}

<span><b>Run Date:</b> {{ test.date.strftime("%Y-%m-%d %H:%M:%S") }}</span>
{{ render_steps(test.steps) }}

app/templates/tests.html
{% from "_macros.html" import render_steps %}

<ul class="collapsible">
    {% for test in tests %}
        <li>
            {% if test.status == "Passed" %}
                {% set row_class = "collapsible-header" %}
            {% elif test.status == "Failed" %}
                {% set row_class = "collapsible-header red lighten-2" %}
            {% elif test.status == "Warning" %}
                {% set row_class = "collapsible-header orange lighten-2" %}
            {% endif %}
            <div class="{{ row_class }}">
                <span style="margin-right: 10px;"><b>Run Date:</b> {{ test.date.strftime("%Y-%m-%d %H:%M:%S") }}</span>
                <span><b>Status:</b> {{ test.status }}</span>
            </div>
            <div class="collapsible-body">
                {{ render_steps(test.steps) }}
            </div>
        </li>
    {% endfor %}
</ul>